/**
 * Shared deal types used by the client page, server generation module,
 * and the refresh CLI script.  All fields are JSON-serializable — the
 * React component for the icon is resolved at render time from `iconName`.
 */

export type DealCategory =
  | "Cruises"
  | "Disney"
  | "All-Inclusive"
  | "Hawaii"
  | "Europe"
  | "Bundles";

export type DealIconName = "Ship" | "Castle" | "TreePalm" | "Plane" | "Globe";

export type DealBadge = "Hot Deal" | "Bonus Commission" | "Exclusive Bundle";

export interface RawDeal {
  id: number;
  title: string;
  destination: string;
  category: DealCategory[];
  image: string;
  description: string;
  perks: string[];
  iconName: DealIconName;
  priceFrom: string;
  priceWas?: string;
  bookBy: string;
  travelWindow: string;
  badge?: DealBadge;
  featured?: boolean;
  /** Supplier name shown as context, e.g. "Royal Caribbean International" */
  supplierName: string;
}

export interface DealsData {
  /** ISO timestamp of the last successful refresh */
  updatedAt: string;
  /** Whether the data was generated by the LLM or the deterministic mock */
  source: "llm" | "mock";
  deals: RawDeal[];
}
